##########################################################################################################################
# ※ 환경 : LOCAL, config.yml
#
#  - 프로젝트 운영에 필요한 내용을 작성한다.
#  - 설정과 관련된 파일은 작성하지 않도록 한다.(application.yml에서 처리)
#
##########################################################################################################################


##########################################################################################################################
# ※시스템 발송용 메일 정보 
#	- address : 이메일 주소
#	- name    : 보내는 이름
##########################################################################################################################

sys:
  sender:
    email:
      address: admin@hamonica.kr
      name: 하모니카

##########################################################################################################################
# ※하모니카 알림 설정
##########################################################################################################################

hamonica:
  plugin:
    enabled: true
    notification:
      enabled: true
      browser:
        enabled: true
      sms:
        enabled: true
      email:
        enabled: true
      slack:
        enabled: true
        workspace-config: [

        ]
      kakao:
        enabled: true